Settings:
  mode: 'PILLAR' #default: 'PILLAR' | PILLAR, EDGE #Note: "EDGE" is not complete implement
  onSneak: true #default: true
  distance:
    height: 12 #default: 12
    height_offset: 2 #default: 2
    width: 2 #default: 2

Blocks:
  - 'oak_log'
  - 'spruce_log'
  - 'birch_log'
  - 'jungle_log'
  - 'acacia_log'
  - 'dark_oak_log'
  - 'oak_wood'
  - 'spruce_wood'
  - 'birch_wood'
  - 'jungle_wood'
  - 'acacia_wood'
  - 'dark_oak_wood'

Tools:
  - 'netherite_axe'
  - 'diamond_axe'
  - 'iron_axe'
  - 'golden_axe'
  - 'stone_axe'
  - 'wooden_axe'